export default {
  ucapan: [
    "Mawar bersemi di batang kayu, do you love me like i love you?🌹",
    "Makan abon pake sapi, i was born to make u happy😊",
    "bunga edelweis bunga lavender, i love you always and forever💘",
    "Makan jelly rasa tomat, literally i miss so much❤️",
    "Bunga bersemi di langit-langit, say you love me like u mean it😉",
    "Kembang mengkudu budidaya argonomi, what can i du to make u love me❤️",
  ],
  panggilan: ["Giyang", "Gita Sayang", "Ayaaaaank", "Gita"],
  colors: [
    "#FF6900",
    "#FCB900",
    "#7BDCB5",
    "#00D084",
    "#8ED1FC",
    "#0693E3",
    "#ABB8C3",
    "#EB144C",
    "#F78DA7",
    "#000000",
    "#833AB4",
    "#FCAF45",
  ],
};
